### ISSUE TITLE
Failed to load the highlight-column package

### ISSUE THREAD

**Issue by JacopoGobbi** [tony612/highlight-column#20]
[Enter steps to reproduce below:]

1. Updated from 0.4.X to 0.5.0
2. Update failed with no message
3. Updated from 0.4.X to 0.5.0
4. Clicked update a second time (mistake)
5. Package updated successfully

Is this a valid issue?

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [highlight-column](https://github.com/tony612/highlight-column) package, v0.5.0

### Stack Trace

Failed to load the highlight-column package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'highlight-column'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'highlight-column'. A type with that name is already registered.
    at Error (native)
    at Object.<anonymous> (/Users/jack/.atom/packages/highlight-column/lib/highlight-column-element.coffee:134:29)
    at Object.<anonymous> (/Users/jack/.atom/packages/highlight-column/lib/highlight-column-element.coffee:139:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/jack/.atom/packages/highlight-column/lib/main.coffee:4:28)
```

### Commands

```
     -0:19.8.0 pane:show-previous-item (div.release-notes.padded.pane-item.native-key-bindings)
     -0:15.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-color-highlight"
    ]
  },
  "highlight-column": {}
}
```

### Installed Packages

```coffee
# User
go-to-view, v0.3.0
highlight-column, v0.5.0
highlight-line, v0.11.0
highlight-selected, v0.10.1
language-haml, v0.21.0
regex-railroad-diagram, v0.8.0
tabs-to-spaces, v0.11.0
vim-mode, v0.53.0

# Dev
No dev packages
```

**Comment by tony612** [comment]
Sorry for this. I'll check this after I upgraded to Atom 1.0

**Comment by tony612** [comment]
I didn't find the error. Can restarting atom or reinstalling highlight-column fix it?

**Comment by JacopoGobbi** [comment]
@tony612 yes, I fixed with both. If you don't find it and think that this can not happen again, close it. Thank you!
