### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by esteban2006** [tony612/highlight-column#24]
[Enter steps to reproduce below:]

1. ...I open Atom, and notice that that are not tabs, so I try to open a file (Ctrl + n will not produce any effect ) so I will have to browse and then open any file 
2. ...then I try to split to the right ... and that is when the message pops u
[Atom failure to open tabs.zip](https://github.com/tony612/highlight-column/files/165749/Atom.failure.to.open.tabs.zip)

3... this happening since I updated Atom

**Atom Version**: 0.187.0-abf368e
**System**: linux 3.13.0-77-generic
**Thrown From**: [highlight-column](https://github.com/tony612/highlight-column) package, v0.5.1

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/eggsteban/.atom/packages/highlight-column/lib/highlight-column-element.coffee:85

TypeError: undefined is not a function
  at highlight-column.HighlightColumnView._cursorPixelRect (/home/eggsteban/.atom/packages/highlight-column/lib/highlight-column-element.coffee:85:27)
  at highlight-column.HighlightColumnView.highlightRect (/home/eggsteban/.atom/packages/highlight-column/lib/highlight-column-element.coffee:75:13)
  at highlight-column.HighlightColumnView.updateHighlight (/home/eggsteban/.atom/packages/highlight-column/lib/highlight-column-element.coffee:54:15)
  at /home/eggsteban/.atom/packages/highlight-column/lib/highlight-column-element.coffee:45:35
  at Config.module.exports.Config.observeKeyPath (/usr/local/share/atom/resources/app/src/config.js:621:7)
  at Config.module.exports.Config.observe (/usr/local/share/atom/resources/app/src/config.js:133:21)
  at highlight-column.HighlightColumnView.handleConfigEvents (/home/eggsteban/.atom/packages/highlight-column/lib/highlight-column-element.coffee:47:35)
  at highlight-column.HighlightColumnView.handleEvents (/home/eggsteban/.atom/packages/highlight-column/lib/highlight-column-element.coffee:19:28)
  at highlight-column.HighlightColumnView.initialize (/home/eggsteban/.atom/packages/highlight-column/lib/highlight-column-element.coffee:7:6)
  at /home/eggsteban/.atom/packages/highlight-column/lib/main.coffee:25:63
  at TextEditor.module.exports.TextEditor.observeCursors (/usr/local/share/atom/resources/app/src/text-editor.js:349:9)
  at /home/eggsteban/.atom/packages/highlight-column/lib/main.coffee:23:14
  at /usr/local/share/atom/resources/app/src/workspace.js:289:16
  at /usr/local/share/atom/resources/app/src/workspace.js:346:18
  at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/local/share/atom/resources/app/src/pane-container.js:379:27)
  at /usr/local/share/atom/resources/app/src/pane-container.js:361:19
  at /usr/local/share/atom/resources/app/src/pane-container.js:127:16
  at Emitter.module.exports.Emitter.emit (/usr/local/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.didAddPane (/usr/local/share/atom/resources/app/src/pane-container.js:319:27)
  at Pane.module.exports.Pane.setContainer (/usr/local/share/atom/resources/app/src/pane.js:111:26)
  at PaneAxis.module.exports.PaneAxis.addChild (/usr/local/share/atom/resources/app/src/pane-axis.js:121:13)
  at PaneAxis.module.exports.PaneAxis.insertChildAfter (/usr/local/share/atom/resources/app/src/pane-axis.js:174:19)
  at Pane.module.exports.Pane.split (/usr/local/share/atom/resources/app/src/pane.js:714:23)
  at Pane.module.exports.Pane.splitRight (/usr/local/share/atom/resources/app/src/pane.js:682:19)
  at atom-pane.atom.commands.add.pane:split-right (/usr/local/share/atom/resources/app/src/pane-element.js:226:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app/src/command-registry.js:246:29)
  at CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/local/share/atom/resources/app/src/command-registry.js:159:19)
  at [object Object].jQuery.fn.trigger (/usr/local/share/atom/resources/app/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/usr/local/share/atom/resources/app/src/window-event-handler.js:80:67)
  at EventEmitter.emit (events.js:119:17)
  at EventEmitter.ipc.sendSync (/usr/local/share/atom/resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/local/share/atom/resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/local/share/atom/resources/app/src/context-menu-manager.js:172:33)
  at HTMLDocument.<anonymous> (/usr/local/share/atom/resources/app/src/window-event-handler.js:153:33)
  at HTMLDocument.handler (/usr/local/share/atom/resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/local/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/local/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -2:01.9 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
  5x -1:56.6 core:backspace (atom-text-editor.editor.mini)
     -1:55.2 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:55.2 core:cancel (atom-text-editor.editor.mini)
  5x -1:51.6 application:new-file (atom-pane.pane.active)
     -1:40.9 application:open-file (atom-pane.pane.active)
  6x -0:06.9 application:new-file (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "the-bespoke-pixel-ui",
      "monokai"
    ]
  },
  "highlight-column": {}
}
```

### Installed Packages

```coffee
# User
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
highlight-column, v0.5.1
monokai, v0.18.0
the-bespoke-pixel-ui, v1.0.4

# Dev
No dev packages
```

**Comment by tony612** [comment]
Please try with latest Atom. 0.187.0 is too old.
