### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pixelRectForScreenRange' of null

### ISSUE THREAD

**Issue by kerryChen95** [tony612/highlight-column#25]
1. open two panels
2. open a file on the left panel
3. open atom's key binding resolver
4. keystroke `cmd-@` which is resolved to command `move-panes:move-right` by user

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [highlight-column](https://github.com/tony612/highlight-column) package, v0.5.1
### Stack Trace

Uncaught TypeError: Cannot read property 'pixelRectForScreenRange' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:439

TypeError: Cannot read property 'pixelRectForScreenRange' of null
    at atom-text-editor.TextEditorElement.pixelRectForScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:439:28)
    at highlight-column.HighlightColumnView._cursorPixelRect (/Users/kerry95/.atom/packages/highlight-column/lib/highlight-column-element.coffee:85:27)
    at highlight-column.HighlightColumnView.highlightRect (/Users/kerry95/.atom/packages/highlight-column/lib/highlight-column-element.coffee:75:13)
    at highlight-column.HighlightColumnView.updateHighlight (/Users/kerry95/.atom/packages/highlight-column/lib/highlight-column-element.coffee:54:15)
    at /Users/kerry95/.atom/packages/highlight-column/lib/highlight-column-element.coffee:45:35
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:612:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:141:21)
    at highlight-column.HighlightColumnView.handleConfigEvents (/Users/kerry95/.atom/packages/highlight-column/lib/highlight-column-element.coffee:47:35)
    at highlight-column.HighlightColumnView.handleEvents (/Users/kerry95/.atom/packages/highlight-column/lib/highlight-column-element.coffee:19:28)
    at highlight-column.HighlightColumnView.initialize (/Users/kerry95/.atom/packages/highlight-column/lib/highlight-column-element.coffee:7:6)
    at /Users/kerry95/.atom/packages/highlight-column/lib/main.coffee:25:63
    at TextEditor.module.exports.TextEditor.observeCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:342:9)
    at /Users/kerry95/.atom/packages/highlight-column/lib/main.coffee:23:14
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:307:16
    at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:372:18
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:388:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:372:28
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:391:20)
    at Object.module.exports.swapEditor (<anonymous>:40:12)
    at Object.module.exports.move (<anonymous>:35:8)
    at Object.module.exports.moveRight (<anonymous>:11:18)
    at atom-workspace.atom.commands.add.move-panes:move-right (<anonymous>:4:70)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  3x -0:19.6.0 core:move-down (atom-text-editor.editor.is-focused)
  7x -0:18.9.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:17 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:17 editor:newline (atom-text-editor.editor.is-focused)
     -0:16.3.0 core:undo (atom-text-editor.editor.is-focused)
     -0:15.8.0 editor:newline-below (atom-text-editor.editor.is-focused)
     -0:06.8.0 core:undo (atom-text-editor.editor.is-focused)
     -0:06.1.0 editor:newline-below (atom-text-editor.editor.is-focused)
     -0:05.5.0 core:undo (atom-text-editor.editor.is-focused)
     -0:01.9.0 move-panes:move-right (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false,
    "followSymlinks": false,
    "packagesWithKeymapsDisabled": [
      "emmet"
    ]
  },
  "highlight-column": {
    "lineMode": true,
    "opacity": 0.05
  }
}
```
### Installed Packages

``` coffee
# User
column-select, v0.2.0
docblockr, v0.7.3
emmet, v2.4.3
highlight-column, v0.5.1
highlight-selected, v0.11.2
keyboard-scroll, v0.4.0
language-babel, v2.16.0
language-vue, v0.9.0
move-panes, v0.2.0
project-manager, v2.7.6

# Dev
No dev packages
```

**Comment by tony612** [comment]
Can't find this right now.
