### ISSUE TITLE
Uncaught TypeError: Cannot read property 'NaN' of undefined

### ISSUE THREAD

**Issue by kevteljeur** [tony612/highlight-column#38]
Atom: 1.19.0-beta1
Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:900

Stack Trace:
```
TypeError: Cannot read property 'NaN' of undefined
    at TextEditorComponent.renderedScreenLineForRow (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:900:37)
    at TextEditorComponent.pixelLeftForRowAndColumn (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:2218:35)
    at TextEditorComponent.pixelPositionForScreenPosition (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-component.js:191:46)
    at HTMLElement.pixelPositionForScreenPosition (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-element.js:243:32)
    at HTMLElement.pixelRectForScreenRange (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor-element.js:254:22)
    at HTMLDivElement.HighlightColumnView._cursorPixelRect (/Users/EC-KT/.atom/packages/highlight-column/lib/highlight-column-element.coffee:85:27)
    at HTMLDivElement.HighlightColumnView.highlightRect (/Users/EC-KT/.atom/packages/highlight-column/lib/highlight-column-element.coffee:75:13)
    at HTMLDivElement.HighlightColumnView.updateHighlight (/Users/EC-KT/.atom/packages/highlight-column/lib/highlight-column-element.coffee:54:15)
    at /Users/EC-KT/.atom/packages/highlight-column/lib/highlight-column-element.coffee:45:35
    at Config.module.exports.Config.observeKeyPath (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:625:13)
    at Config.module.exports.Config.observe (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/config.js:150:27)
    at HTMLDivElement.HighlightColumnView.handleConfigEvents (/Users/EC-KT/.atom/packages/highlight-column/lib/highlight-column-element.coffee:47:35)
    at HTMLDivElement.HighlightColumnView.handleEvents (/Users/EC-KT/.atom/packages/highlight-column/lib/highlight-column-element.coffee:19:28)
    at HTMLDivElement.HighlightColumnView.initialize (/Users/EC-KT/.atom/packages/highlight-column/lib/highlight-column-element.coffee:7:6)
    at /Users/EC-KT/.atom/packages/highlight-column/lib/main.coffee:25:63
    at TextEditor.module.exports.TextEditor.observeCursors (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:744:15)
    at /Users/EC-KT/.atom/packages/highlight-column/lib/main.coffee:23:14
    at /Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:721:22
    at Function.module.exports.Emitter.simpleDispatch (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at /Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:594:34
    at /Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:595:19
    at Function.module.exports.Emitter.simpleDispatch (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PaneContainer.didAddPaneItem (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/pane-container.js:270:24)
    at PaneContainer.didAddPane (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/pane-container.js:242:18)
    at Pane.module.exports.Pane.setContainer (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:162:32)
    at PaneAxis.module.exports.PaneAxis.addChild (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/pane-axis.js:154:19)
    at PaneAxis.module.exports.PaneAxis.insertChildAfter (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/pane-axis.js:225:25)
    at Pane.module.exports.Pane.split (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:1004:29)
    at Pane.module.exports.Pane.splitRight (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:964:25)
    at HTMLElement.pane:split-right-and-copy-active-item (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/register-default-commands.js:269:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/atom-environment.js:1344:34)
    at EventEmitter.outerCallback (/Users/EC-KT/Applications/Atom Beta.app/Contents/Resources/app/src/application-delegate.js:347:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

This is probably related to the new rendering system.

**Comment by kevteljeur** [comment]
Actually, it seems that you've fixed it now. Release the new version! Release!

Thanks for a great little module. Really helps me see what I'm doing.

**Comment by JohnMurga** [comment]
Copy https://raw.githubusercontent.com/JohnMurga/highlight-column/master/lib/highlight-column-element.coffee over the old one to try ...

**Comment by kevteljeur** [comment]
@JohnMurga Thanks, will try it out.

**Comment by kevteljeur** [comment]
@JohnMurga's fix does indeed solve the problem.

**Comment by bennypowers** [comment]
Hi I have this problem on latest (0.5.4). Can this fix be released?
